### ISSUE TITLE
Embedded images in PDF

### ISSUE THREAD

**Issue by Ncedia** [cajuncoding/ApacheFOP.Serverless#2]
Hello!

Thanks for your nice solution for generating PDF's in Azure.
Is there support for embedding images with <fo:external-graphic src="image.png"/>?
If not, is it possible to add this lib?

/Jonas

**Comment by cajuncoding** [comment]
I’m really glad your getting value from the project!  If you like it please give it a Star (their free)!

Yes ApacheFOP supports images that are:
- Readily accessible (non-secured) via http url
- Embedded direclty into the Xsl-Fo markup as Base64 encoded image
   -https://stackoverflow.com/a/10373244/7293142

Both work as expected.

**Comment by Ncedia** [comment]
Great!!! (It's working now)

Thanks!!!
