### ISSUE TITLE
Recommendation for custom font inclusion.

### ISSUE THREAD

**Issue by MichaelYabko** [cajuncoding/ApacheFOP.Serverless#4]
Hi there,

I was wondering if you could make any recommendations for embedding custom fonts when the service is running in Azure.

**Comment by cajuncoding** [comment]
Per the Apache FOP documentation you can register fonts (custom fonts) with Apache FOP for reference within your XslFO markup:
https://xmlgraphics.apache.org/fop/2.1/fonts.html#register

In addition there are more details [here where they provide all configuration elements](https://xmlgraphics.apache.org/fop/2.6/configuration.html), whereby you can set the base path via `font-base` param for all Fonts paths to be relative to when loading/registering.

So with the configuration of those elements then you can register any font you like with ApachFOP when it loads.

Specifically in ApacheFOP.Serverless, the configuration xml file is loaded automatically from a resource file that is deployed with the Java Azure Function via the `resources` folder; you'll find it in the project path: `/src/main/resources/apache-fop-config.xml`

This file is loaded by the framework automatically and provided to ApacheFOP upon initialization.

So, I believe you can drop in your custom files into the resource folder as `src/main/resource/{fontfile.ttf}`, and then configure that path correctly in the `apache-fop-config.xml` file so it is found by ApacheFOP per the documentation.

Thus far I've not tried/validated this myself, so let me know how you get along with this . . . eventually when I get some time (may not be this week) I can try to test/validate with an example -- but the crux will just be determining what the full file path to a font file in the `resources` folder is after being deployed to Azure Functions and/or what the relative base Url configuration needs to be.

Good Luck!

**Comment by cajuncoding** [comment]
@MichaelYabko 
Ok, so it wasn't quite as straightforward as I hoped, but with a little more help now it is :-)

I've pushed the latest v1.2 (with readme updates)... which now supports a much easier way to include your TTF/OTF/etc. custom font files, and easily register them in configuration.

More details are now in the readme here: https://github.com/cajuncoding/ApacheFOP.Serverless#custom-fonts-via-resource-files

It's definitely working, here's a sample from my personal deployment in Azure via Postman:
![image](https://user-images.githubusercontent.com/20844814/135413028-bf5932bb-77df-402e-bb5f-44a93143bd4b.png)

**Comment by MichaelYabko** [comment]
This is really cool @cajuncoding. One other thing that we also found works was to include the fonts in the config as a url. Then we setup an azure storage link for each of the fonts. Gonna try this out shortly.

Thanks 👍

**Comment by MichaelYabko** [comment]
works great :-)

**Comment by cajuncoding** [comment]
Yes, that's correct, I can now confirm that if you have font file directly downloadable anonymously by url then the original/default resource resolver will work.  I've now learned that It is the same resolver used for all external resources when Apache FOP processes it's configuration as well as when rendering the markup (e.g. images)!
